FROM node:lts-alpine AS builder
ARG NPM_USERNAME
ARG NPM_PASSWORD
ARG NPM_EMAIL
ARG BRANCH_OR_TAG

# Install the latest versions from edge
RUN sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories && \
    apk add --upgrade bash git make gcc g++ openssh-client python3 jq && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*

# Add deployment key and authenticate into npm/pkg.form.io
RUN mkdir /root/.ssh/ && ssh-keyscan github.com >> /root/.ssh/known_hosts
ADD id_ed25519 /root/.ssh/id_ed25519
RUN chmod 600 /root/.ssh/id_ed25519
RUN npm i -g npm-cli-login
RUN npm-cli-login -u $NPM_USERNAME -p $NPM_PASSWORD -e $NPM_EMAIL -r https://pkg.form.io
RUN echo "@formio:registry=https://pkg.form.io" > .npmrc

# TODO: IF BRANCH_OR_TAG IS 'local' mount the local formio-server repo
RUN git clone --single-branch --branch $BRANCH_OR_TAG git@github.com:formio/formio-server.git /src
WORKDIR /src
RUN yarn install --frozen-lockfile

# Install the portal application at the correct branch or tag
RUN jq -r '.portalVersion' package.json | xargs -I {} git clone --single-branch --branch {} git@github.com:formio/formio-app.git
WORKDIR /src/formio-app
RUN yarn install --frozen-lockfile
RUN yarn build:dev
WORKDIR /src
RUN mkdir -p /src/portal && cp -r formio-app/dist/* /src/portal

# Clean up sensitive data
RUN rm /root/.npmrc \
    && rm -fr /root/.ssh \
    && rm -rf /src/id_ed25519 \
    && find / -xdev -type l ! -exec test -e {} \; -delete

FROM node:lts-alpine

ENV USERNAME=formiouser
ENV UID=5000
ENV GROUP=${USERNAME}
ENV GID=${UID}

RUN adduser -u ${UID} -g ${GROUP} -D ${USERNAME} &&\
    addgroup ${USERNAME} ${GROUP}

COPY --from=builder /src /src

# Cleanup
RUN rm -rf /var/lib/apt/lists/* &&\
    rm -f /etc/fstab &&\
    crontab -r &&\
    find / -name wget -delete &&\
    rm -fr /etc/init.d /lib/rc /etc/conf.d /etc/inittab /etc/runlevels /etc/rc.conf /etc/logrotate.d &&\
    rm -fr /etc/sysctl* /etc/modprobe.d /etc/modules /etc/mdev.conf /etc/acpi && \
    find /bin /etc /lib /sbin /usr -xdev -type f -a \( -perm +4000 -o -perm +2000 \) -delete &&\
    find / -xdev -type l ! -exec test -e {} \; -delete

WORKDIR     /src

RUN apk add libcap && setcap 'cap_net_bind_service=+ep' $(which node)
USER ${USERNAME}

EXPOSE 3000
CMD  ["node", "--no-node-snapshot", "--inspect=0.0.0.0", "main.js"]
