services:
  formio-server-development:
    image: formio-server-development:${BRANCH_OR_TAG}
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile-development
      args:
        - BRANCH_OR_TAG=${BRANCH_OR_TAG}
        - NPM_USERNAME=${NPM_USERNAME}
        - NPM_PASSWORD=${NPM_PASSWORD}
        - NPM_EMAIL=${NPM_EMAIL}
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      PORTAL_ENABLED: 1
      ADMIN_EMAIL: brendan@form.io
      ADMIN_PASS: Sanford1f!
      MONGO: mongodb://host.docker.internal:27017/formio
    env_file:
      - .env
