version: '3.7'
services:
  mongo:
    image: mongo:4.1
    restart: always
    volumes:
      - mdb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
  formio:
    image: formio/formio-enterprise
    restart: always
    links:
      - mongo
    ports:
      - "3000:80"
    environment:
      PORTAL_ENABLED: 1
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASS: CHANGEME
      LICENSE:
volumes:
  mdb-data:
