FROM node:6-alpine
MAINTAINER Form.io <support@form.io>

COPY ./build /src
WORKDIR /src

# Install git
RUN apk update && \
    apk upgrade && \
    apk add --no-cache --virtual .build-deps bash git make gcc g++ python openssh

# Add deployment keys
RUN mkdir /root/.ssh/
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts
ADD deployment/keys/formio-services /root/.ssh/id_rsa

RUN npm install --production --build-from-source=bcrypt && \
    npm cache clean && \
    npm uninstall -g npm && \
    apk del .build-deps

# Remove deployment keys.
RUN rm -f /root/.ssh/id_rsa && rm -rf deployment/keys

EXPOSE      80
ENTRYPOINT  ["node", "--max_old_space_size=4096", "--debug=5858", "main"]
